# Generated by Django 4.2.7 on 2023-11-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='SLug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Content/images/%Y/%m/%d/', verbose_name='Image')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Dernière Modification')),
                ('created_on', models.DateField(auto_now_add=True, null=True, verbose_name='Creation à')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('internet', models.BooleanField(default=False, verbose_name='internet')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_on'],
            },
        ),
    ]
